### PR TITLE
HD-344: added ogit/Auth/Account mapping

### PR DESCRIPTION
**Pull request by miraage**
Added ogit/Auth/Account, updated base auth strategy.

### CODE REVIEW

**Comment by miraage** [comment]
@bpneal please review

**Comment by bpneal** [comment]
Can the versions in the package.jsons for each changed project also be bumped to the next major version please. This way we ensure, that older projects won't break.
ie. https://github.com/arago/hiro-graph-js/blob/master/packages/hiro-graph-implicit-oauth/package.json#L3

**Comment by bpneal** [comment]
Also, does anyone from Klika have an NPM account, as I can give you permission to deploy there too

**Comment by miraage** [comment]
@bpneal yeah, `miraage` is mine.

**Comment by miraage** [comment]
So, I'll publish as soon as you merge this. Anything we wanna add in this PR?

**Pull request merged**
